name: Deploy Chat-application on server

on:
  push:
    branches: [main, develop, master]
    paths:
      - "backend/**"

  pull_request:
    branches: [main, master]
    paths:
      - "backend/**"

jobs:
  test:
    name: Test (${{ matrix.service }})
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd="rabbitmq-diagnostics check_running"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    strategy:
      fail-fast: false
      matrix:
        service: [ user, mail]

    defaults:
      run:
        working-directory: backend/services/${{ matrix.service }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: backend/services/${{ matrix.service }}/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm run test --if-present
        env:
          REDIS_HOST: 127.0.0.1
          REDIS_PORT: 6379

          RABBITMQ_HOST_NAME: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

          MONGO_URL: ${{ secrets.MONGO_URL }}

          EMAIL_HOST_NAME: smtp.gmail.com
          EMAIL_HOST_USERNAME: ${{ secrets.EMAIL_HOST_USERNAME }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          TURNSTILE_SECRET_KEY: ${{ secrets.TURNSTILE_SECRET_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_CLOUD_SECRET: ${{ secrets.CLOUDINARY_CLOUD_SECRET }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CORS_ORIGIN: ${{ secrets.CORS_ORIGIN }}

      - name: Build
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR Repository if not exists
        run: |
          aws ecr describe-repositories \
            --repository-names chat-${{ matrix.service }} \
            || aws ecr create-repository \
            --repository-name chat-${{ matrix.service }}
      
      - name: Build Docker Image
        run: |
          docker build \
            -t chat-${{ matrix.service }} \
            .
      
      - name: Tag Docker Image
        run: |
          docker tag chat-${{ matrix.service }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/chat-${{ matrix.service }}:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/chat-${{ matrix.service }}:${{ github.sha }}